Draft translate to korean
sanic-org/sanic-guide pull request #20
Opened 2021-03-21 10:05 UTC by SaidBySolo

2021-03-21 10:21 UTC, ahopkins commented
Awesome. Let @sanic-org/docs know if you have any questions or run into any problems.

2021-03-21 10:46 UTC, ZinkLu commented
Great! Let us know if you have any issue in doc content or vuepress.

2021-03-21 23:15 UTC, wonderlandpark requested changes

2021-03-21 23:15 UTC, wonderlandpark commented on src/ko/guide/README.md
> +## Contribution
```suggestion
## 기여
```

2021-03-21 23:15 UTC, wonderlandpark commented on src/ko/guide/README.md
> +## 이게 뭐야?
How about this
```suggestion
## 이게 뭔가요?
```

2021-03-26 05:40 UTC, miss85246 commented
Haha, we have to support one more language, let sanic guide become more powerful 🎸

2021-03-26 09:28 UTC, ahopkins commented
Waiting for @vltr to translate it to Portuguese.

2021-04-06 09:42 UTC, ahopkins commented
@SaidBySolo How's it coming? Do you need anything from us non-Korean speakers?

2021-04-06 11:54 UTC, SaidBySolo commented
> @SaidBySolo 어떻게 되나요? 한국어가 아닌 우리에게 필요한 것이 있습니까?

Progress is slowing due to academic problems. :(

i am aim to work so that we can merge by the end of next month!

2021-04-13 02:26 UTC, miss85246 commented
Come on！ we support you in spirit
힘내, 우리는 정신적으로 너를 지지한다
@SaidBySolo

2021-04-24 16:54 UTC, SaidBySolo commented
@sanic-org/docs

Is it okay to divide the pull request by part?
If I am lucky, I will finish the Basic part today.

2021-04-25 06:12 UTC, ahopkins commented
Yeah. That works for me.

2021-12-01 09:21 UTC, ahopkins commented
Where do we stand with this?

2021-12-01 09:50 UTC, SaidBySolo commented
> Where do we stand with this?


It seems that all the basic parts of version 21.3 have been completed in the local commit.
I will open a PR tomorrow after merging upstream and making corrections.

2021-12-01 11:48 UTC, SaidBySolo commented
Okay, I have time, so I finished today. 
If I have time, I will definitely work on the rest.

Based on this PR, I hope that other Koreans will also be interested in sanic.

ps. Sorry for taking so long. I forgot this PR. :(

2021-12-01 12:14 UTC, ahopkins approved these changes

2021-12-01 12:14 UTC, merged

2021-12-01 12:15 UTC, ahopkins commented
:clap: :champagne: 
Thanks for all the work on this!