Update nginx.md
sanic-org/sanic-guide pull request #39
Opened 2021-05-03 07:07 UTC by Tronic

- Fix inconsistent indent in nginx conf (now following the style of https://www.nginx.com/resources/wiki/start/topics/examples/full/)
- Update comment on websocket section because it is also needed for pipelining
- Remove $ from shell commands so that they can be copy&pasted directly
- Highlight the paragraph about main nginx.conf, relevant for Arch, Windows and others

2021-05-03 07:08 UTC, Tronic commented
I didn't try how this renders, in particular, for the note highlight added. Does the docs site offer a proper solution for note/tip boxes?

2021-05-04 23:54 UTC, miss85246 commented
@Tronic 
Thank you for your contribution
could you also modify `nginx.md` under zh folder ? if there need some content need to translate, please skip it, I will translate it latter.
about the notes/tip boxes, you can see this [documentation](https://vuepress.vuejs.org/guide/markdown.html#custom-containers)

2021-05-05 09:07 UTC, ahopkins commented
@Tronic, it should be easy to get it up and running locally if you want:

```bash
yarn
make dev
```

2021-05-05 09:10 UTC, ahopkins requested changes

2021-05-05 09:10 UTC, ahopkins commented on src/en/guide/deployment/nginx.md
> +> **❕ NOTE:** For installs that don't use `conf.d` and `sites-available`, all of the above
```
::: note
For installs ...
:::
```

2021-05-05 18:32 UTC, ahopkins commented
> Note in a box. 

Possibly the best commit message I've ever seen. 😆

2021-05-05 18:33 UTC, ahopkins approved these changes

2021-05-05 18:34 UTC, ahopkins commented
@sanic-org/docs Do you want to review Chinese now, or add as separate PR.

2021-05-05 20:20 UTC, Tronic commented
> > Note in a box.
> 
> Possibly the best commit message I've ever seen. 😆

Purely accidental too 📦

2021-05-06 02:05 UTC, merged

2021-05-06 02:06 UTC, miss85246 commented
@Tronic @ahopkins good work 👍🏼