Add documentation on partial segment matching
sanic-org/sanic-guide pull request #40
Opened 2021-05-05 01:01 UTC by miss85246

modify `routing.md` file to add segment matching part

2021-05-05 01:07 UTC, miss85246 commented
![image](https://user-images.githubusercontent.com/42527535/117087181-4c742a80-ad81-11eb-9fe4-336d7786045b.png)

2021-05-05 06:30 UTC, ahopkins requested changes
This is super helpful. I am somewhat reluctant to hide it away in the regex tab.

What do you think about adding a new subsection after the tabs for "Partial segment matching"? And instead having a mention in the regex tab to "see below" for more details?

2021-05-05 06:30 UTC, ahopkins commented on src/en/guide/basics/routing.md
> +If you wanted to match the file pattern, but only capture the numeric portion, you need to do some regex fun:
Feels like we needs some emoji here to make it more "fun" :smile: Who doesn't like seeing more emojis :flags:

2021-05-05 06:30 UTC, ahopkins commented on src/en/guide/basics/routing.md
> +app.route(r"/image/<img_id:(?P<img_id>\d+)\.jpg>")
I think we should offer this as the standard pattern and not scare anyone away with named matching if we do not need to:

```python
app.get(r"/<foo:(\d+).jpg>")
```

2021-05-05 06:30 UTC, ahopkins commented on src/en/guide/basics/routing.md
> +@app.get(r"/<foo:(?P<foo>[a-z]{3}).(?:txt)>")   # defining a single named matching group, with one or more non-matching groups
I think we should make all of these examples use the `\d+` with `jpg` pattern for consistency with the first example we give.

Maybe the last one can be an exception and be a little different:

```python
r"/<foo:(?P<foo>\d+).(?:jpg|png)>
```

2021-05-05 06:30 UTC, ahopkins commented on src/en/guide/basics/routing.md
> +
> Therefore, we can see that when using regex routing, we have 4 options:

2021-05-05 06:30 UTC, ahopkins commented on src/en/guide/basics/routing.md
> +Also, if using a named matching group, it must be the same as the segment label.
```
app.get(r"/<foo:(?P<foo>\d+).jpg>")  # OK
app.get(r"/<foo:(?P<bar>\d+).jpg>")  # NOT OK
```

2021-05-06 02:09 UTC, miss85246 commented
good idea, I will add a new subsection in my free time 😄

2021-07-19 06:42 UTC, closed without merging