How-to page for static redirects
sanic-org/sanic-guide pull request #63
Opened 2021-08-13 17:56 UTC by Perzan

2021-08-13 18:55 UTC, sjsadowski commented
I took a look at this and I like where it's going, but this seems like an overly complicated example for what should be a relatively straightforward item. 

Perhaps you could add a simple section and use this as an 'advanced' section?

@sanic-org/core-devs thoughts?

2021-08-15 04:44 UTC, ahopkins requested changes
Looks great, thanks for this. Can you also add to `.vuepress/config.js` to add it to the sidebar?

2021-08-15 04:44 UTC, ahopkins commented on src/en/guide/how-to/toc.md
> +| [Static redirects](./static-redirects) | ... configure static redirects? |
can you move this up so it's in alphabetical order?

2021-08-15 04:44 UTC, ahopkins commented on src/en/guide/how-to/static-redirects.md
> +def get_static_function(value:object) -> typing.Callable[..., object]:
`Any` is a better annotation than `object`. But since it is meant to return a route handler there is an annotation for that in `sanic.models`

2021-08-16 05:14 UTC, ahopkins commented
> I took a look at this and I like where it's going, but this seems like an overly complicated example for what should be a relatively straightforward item.
> 
> Perhaps you could add a simple section and use this as an 'advanced' section?
> 
> @sanic-org/core-devs thoughts?

What do you find to be overly complicated? There really is no need for this:

```python
def get_static_function(value:typing.Any) -> typing.Callable[..., typing.Any]:
    return lambda *_, **__: value
```

2021-08-16 12:45 UTC, sjsadowski commented
> What do you find to be overly complicated? There really is no need for this:
> 
> ```python
> def get_static_function(value:typing.Any) -> typing.Callable[..., typing.Any]:
>     return lambda *_, **__: value
> ```

That's specifically what I was referencing, though I mis-followed the codepath when the REDIRECTS k,v was getting split. I withdraw my statement... I'm fine with this.

2021-08-16 13:31 UTC, ahopkins commented
804 KB is a bit big. Can we get a smaller image to use in this example?

2021-08-16 16:54 UTC, ahopkins approved these changes

2021-08-16 16:54 UTC, merged

2021-08-16 17:13 UTC, ahopkins commented
@Perzan Thanks for contributing this :muscle:

2021-08-17 22:30 UTC, Perzan commented
Certainly, thanks for the approval